working on pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -86,10 +86,11 @@ configure_nginx:
 # Этап для тестирования
 run_tests:
   stage: test
-  image: python:3.12
-  before_script:
-    - python -V
-    - pip install -U pip
-    - pip install -r requirements.txt
+  tags:
+    - shell
   script:
-    - python manage.py test --noinput
+    - ssh root@$SERVER_HOST "cd /opt/django_app/ && docker compose exec -T django-app python manage.py test --noinput"
+    - if [ $? -ne 0 ]; then
+        echo "Tests failed";
+        exit 1;
+      fi
